---
name: Rubocop

on: [pull_request, workflow_dispatch]

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run rubocop
        run: |
          PATH="$(ruby -r rubygems -e 'puts Gem.user_dir')/bin:$PATH"
          echo $PATH
          gem install --user-install rubocop -v=0.93.1
          rubocop